### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Newel-86**

### CODE REVIEW

**Comment by florim1213** [comment]
https://MineIn.Cloud/bonus?r=72255

**Review by siruschavoshi — APPROVED** [review]

**Comment by evandrofgarcia** [comment]
Thank my friend!👍

**Comment by evandrofgarcia** [comment]
This is Pi !

**Comment by 0912470398** [comment]
😮😮

**Comment by 0912470398** [comment]
😊😊😊😊

**Comment by florim1213** [comment]
https://noones.com/user/ManlyHagfish54

**Comment by florim1213** [comment]
https://noones.com/user/ManlyHagfish54

**Comment by kalumunafaustine** [comment]
Thanks too, what are you dealing with

**Comment by Syedibbadulhaq** [comment]
Why

**Comment by evandrofgarcia** [comment]
Very good

**Comment by kalumunafaustine** [comment]
I would like to know what you will be offering with your company after Pi
open minet sir

**Comment by florim1213** [comment]
stake.com/?c=BJVPQFu4

**Comment by Newel-86** [comment]
Hoffe es geht noch was im diesem Jahr 😜

**Comment by S9393** [comment]
***@***.***

**Comment by florim1213** [comment]
https://TONFree.win/?r=99933

**Pull request closed without merging**
