### PR TITLE
Jp translation

### PR DESCRIPTION
**Pull request by Thienan007**

### CODE REVIEW

**Review by Thienan007 — COMMENTED** [review]
Dev

**Comment by Thienan007** [comment]
Dev

**Comment by Thienan007** [comment]
Dev

**Comment by Thienan007** [comment]
C

**Review by tranthithoa0803 — COMMENTED** [review]
Ok

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Review by Thienan007 — COMMENTED** [review]
Ok

**Comment by HTC37** [comment]
gh pr checkout 41

**Pull request closed without merging**
