### PR TITLE
Create Rex

### PR DESCRIPTION
**Pull request by Fredrexee**

### CODE REVIEW

**Review by rolanasser — APPROVED** [review]

**Comment by rolanasser** [comment]
👍

**Comment by andijava80** [comment]
Nice

**Comment by Ukachukwu1** [comment]
Cool

**Comment by 33Yahya33** [comment]
Nice

**Comment by rolanasser** [comment]
Nice

**Review by Dome79 — APPROVED** [review]

**Comment by 870Ninja** [comment]
Approve these changes great job!

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Pull request closed without merging**
