### PR TITLE
add Hausa translation

### PR DESCRIPTION
**Pull request by dev-king21**

### CODE REVIEW

**Review by InesM810 — COMMENTED** [review]
That is amazing

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Review by Ahmedjamal66 — APPROVED** [review]

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Review by Winds126 — APPROVED** [review]

**Review by blmitkc — APPROVED** [review]

**Review by blmitkc — APPROVED** [review]

**Comment by rahish09** [comment]
Thank you for your response

**Comment by florim1213** [comment]
https://TONFree.win/?r=99933

**Comment by florim1213** [comment]
https://TONFree.win/?r=99933

**Comment by florim1213** [comment]
https://TONFree.win/?r=99933

**Review by Winds126 — APPROVED** [review]

**Pull request merged**
