### PR TITLE
Dependabot/npm and yarn/follow redirects 1.14.9

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
[]()

**Comment by Canda4c** [comment]
I don't understand what is going on here

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Watch git hub you tube channel

**Comment by RadGog** [comment]
Okay

вс, 11 сент. 2022 г., 18:43 Deleted user ***@***.***>:

**Comment by Daibao9999** [comment]
{
  "_links": {
    "self": {
      "href": "https://horizon.stellar.org/operations/189395228687142914"
    },
    "transaction": {
      "href": "https://horizon.stellar.org/transactions/ac867093e89b1677d9441fb9fceb86619cf16d820523c954f7b7703b5cdfab0d"
    },
    "effects": {
      "href": "https://horizon.stellar.org/operations/189395228687142914/effects"
    },
    "succeeds": {
      "href": "https://horizon.stellar.org/effects?order=desc\u0026cursor=189395228687142914"
    },
    "precedes": {
      "href": "https://horizon.stellar.org/effects?order=asc\u0026cursor=189395228687142914"
    }
  },
  "id": "189395228687142914",
  "paging_token": "189395228687142914",
  "transaction_successful": true,
  "source_account": "GCM2EEW5CIANDVK3AVTS37AKOJHKS23YL25MRU57BLDWGEUQH5E4QGMW",
  "type": "manage_buy_offer",
  "type_i": 12,
  "created_at": "2022-12-20T07:24:22Z",
  "transaction_hash": "ac867093e89b1677d9441fb9fceb86619cf16d820523c954f7b7703b5cdfab0d",
  "amount": "0.0000050",
  "price": "222286.0167374",
  "price_r": {
    "n": 942937283,
    "d": 4242
  },
  "buying_asset_type": "credit_alphanum4",
  "buying_asset_code": "BTC",
  "buying_asset_issuer": "GDPJALI4AZKUU2W426U5WKMAT6CN3AJRPIIRYR2YM54TL2GDWO5O2MZM",
  "selling_asset_type": "native",
  "offer_id": "1133588110"
}

**Review by Daibao9999 — COMMENTED** [review]
package-lock.json

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
[]()

**Comment by Anil3781** [comment]
How can I transaction my account

**Comment by Anil3781** [comment]
How I transfer amount to my account, I have no idea.
Please guide me 🙏

**Comment by EarlyFunds** [comment]
Who did this  transaction?

**Comment by Anil3781** [comment]
I don't know.
But I want it

**Pull request closed without merging**
