### PR TITLE
nanis94-yama-1

### PR DESCRIPTION
**Pull request by nanis94**

### CODE REVIEW

**Comment by nanis94** [comment]
nanis94:development

**Review by nanis94 — COMMENTED** [review]
.github/workflows/datadog-synthetics.yml

**Comment by nanis94** [comment]
nanis94:development

**Comment by nanis94** [comment]
nanis94:development

**Review by nanis94 — COMMENTED** [review]
.github/workflows/datadog-synthetics.yml

**Comment by nanis94** [comment]
nanis94:development

**Comment by nanis94** [comment]
nanis94:development

**Comment by nanis94** [comment]
main

**Review by nanis94 — COMMENTED** [review]
comment

**Comment by RamadanHash** [comment]
👍

**Pull request closed without merging**
