### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by Hurrabbas12**

### CODE REVIEW

**Comment by willianr2304** [comment]
✌️

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Review by FukYaMudda — APPROVED** [review]

**Review by MBDGrootCCRN — APPROVED** [review]

**Review by Freedom188 — APPROVED** [review]

**Comment by AuwalIsmail07** [comment]
Hello I Auwal Ismail from kano city Nigeria how can I pi kyc? Thank you so
much and best regard

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Comment by jy01099548** [comment]
我来自中国🇨🇳大陆，我是第一批kyc现在显示Sorry.

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
ok

**Comment by RamadanHash** [comment]
Ok

**Comment by tuannguyenphucan1991** [comment]
Được gửi từ iPhone của tôi

**Review by Freedom188 — APPROVED** [review]

**Comment by willianr2304** [comment]
Como recebo o dinheiro alguem pode ajudar

**Review by FukYaMudda — APPROVED** [review]

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
ok

**Review by Freedom188 — APPROVED** [review]

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
ok

**Comment by huynhthienphan** [comment]
GBA3HCSH5LUFJPOYTKTIOBDXIGP7QU7XH67Y6GMWWA65FZFZU32PWJ6W

**Comment by Mhaji578** [comment]
How pi kvc

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
When you browse in pi browser pi kyc application will come then you have to fill it  with the help of your I'd card

**Comment by Dome79** [comment]
GBZ2THJDVMRM4QEKYAXTCOOM3LKUN3ZXCCJRMXE7ZXN6E4US5NXHFW3Q

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Comment by Khaseem12** [comment]
GC5R3DDZULPJZX3254R4Q5SP4JKTJ6BFF2OGOOHEXTWOA5DX7GFLXVUH

**Pull request closed without merging**
