### PR TITLE
Anchor asset should clean up that is not related in pi blockchain

### PR DESCRIPTION
**Pull request by 0205miss**

### CODE REVIEW

**Comment by glenn05** [comment]
remove

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Review by Abdulsamadbawar — COMMENTED** [review]
Hi

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Comment by Amol5610** [comment]
Hy

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Hello

**Comment by pi666666** [comment]
完美

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Hello

**Comment by ghest28** [comment]
Hallo

Pada tanggal Sab, 21 Mei 2022 16.42, V1e2n3k4a5t6e7s8w9a10r11l12u13 <
***@***.***> menulis:

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Comment by 883355** [comment]
Hi

دریافت Outlook برای Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Hello

**Comment by gpn-98** [comment]
Ok

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Hi

**Comment by RamadanHash** [comment]
Ok

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Review by Freedom188 — APPROVED** [review]

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Hi

**Review by frolink — APPROVED** [review]

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Comment by Freedom188** [comment]
👀

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
[]()

**Review by Freedom188 — APPROVED** [review]

**Review by Freedom188 — APPROVED** [review]

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Review by Freedom188 — APPROVED** [review]

**Review by Freedom188 — APPROVED** [review]

**Review by Freedom188 — APPROVED** [review]

**Review by Freedom188 — APPROVED** [review]

**Review by Freedom188 — APPROVED** [review]

**Review by Freedom188 — APPROVED** [review]

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Review by kanskecelina — APPROVED** [review]

**Review by kanskecelina — APPROVED** [review]

**Review by Freedom188 — APPROVED** [review]

**Review by Freedom188 — APPROVED** [review]

**Review by Freedom188 — APPROVED** [review]

**Comment by tuannguyenphucan1991** [comment]
Được gửi từ iPhone của tôi

**Comment by HTC37** [comment]
gh pr checkout 21

**Review by HTC37 — COMMENTED** [review]
gh pr checkout 21

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
[]()

**Comment by SALMAS999** [comment]
hello  everybody

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
[]()

**Comment by Anil3781** [comment]
Hello

**Comment by 3TheeOnly3Goldie** [comment]
> 
> 
> Được gửi từ iPhone của tôi
> 
> > Vào ngày 24 thg 7, 2022, lúc 12:16, V1e2n3k4a5t6e7s8w9a10r11l12u13 ***@***.***> đã viết:
> > 
> > ﻿
> > Ok
> > 
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you are subscribed to this thread.
> 

What is this thread referring to?

**Comment by Anil3781** [comment]
Thank you

**Review by HTC37 — COMMENTED** [review]
gh pr checkout 21

**Comment by Majdian** [comment]
Hi der nice to meet you 
My pi network I'd: Majdian1355

**Comment by fakhroshumailasabri786** [comment]
Plz Gide me whay use this file I'm not smart so help pkz

**Comment by fakhroshumailasabri786** [comment]
End thankx for Gmail

**Comment by Anil3781** [comment]
Thank you!

**Review by haticecan37 — COMMENTED** [review]
src/data/directory.json

**Comment by aminghorbani1986** [comment]
در تاریخ پنجشنبه ۱۹ اکتبر ۲۰۲۳،‏ ۸:۰۲ HTC☯️⚛️NFT ***@***.***>
نوشت:

**Review by Brandonlb91 — APPROVED** [review]

**Comment by abas929** [comment]
السلام عليكم

**Pull request closed without merging**
